######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 16 17:25:20 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include
INCLUDEPATH += . include

# Input
HEADERS += include/complex.h include/exceptions.h
SOURCES += complex.cpp exceptions.cpp main.cpp
