######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 14 16:46:16 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += complex.h \
    exceptions.h
SOURCES += complex.cpp main.cpp \
    exceptions.cpp
