######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 16 21:27:31 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include src
INCLUDEPATH += . include

# Input
HEADERS += include/complex.h include/exceptions.h
SOURCES += src/complex.cpp src/exceptions.cpp src/main.cpp

